// Code generated by go-swagger; DO NOT EDIT.

package delete_truck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteTruckParams creates a new DeleteTruckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTruckParams() *DeleteTruckParams {
	return &DeleteTruckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTruckParamsWithTimeout creates a new DeleteTruckParams object
// with the ability to set a timeout on a request.
func NewDeleteTruckParamsWithTimeout(timeout time.Duration) *DeleteTruckParams {
	return &DeleteTruckParams{
		timeout: timeout,
	}
}

// NewDeleteTruckParamsWithContext creates a new DeleteTruckParams object
// with the ability to set a context for a request.
func NewDeleteTruckParamsWithContext(ctx context.Context) *DeleteTruckParams {
	return &DeleteTruckParams{
		Context: ctx,
	}
}

// NewDeleteTruckParamsWithHTTPClient creates a new DeleteTruckParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTruckParamsWithHTTPClient(client *http.Client) *DeleteTruckParams {
	return &DeleteTruckParams{
		HTTPClient: client,
	}
}

/*
DeleteTruckParams contains all the parameters to send to the API endpoint

	for the delete truck operation.

	Typically these are written to a http.Request.
*/
type DeleteTruckParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete truck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTruckParams) WithDefaults() *DeleteTruckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete truck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTruckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete truck params
func (o *DeleteTruckParams) WithTimeout(timeout time.Duration) *DeleteTruckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete truck params
func (o *DeleteTruckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete truck params
func (o *DeleteTruckParams) WithContext(ctx context.Context) *DeleteTruckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete truck params
func (o *DeleteTruckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete truck params
func (o *DeleteTruckParams) WithHTTPClient(client *http.Client) *DeleteTruckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete truck params
func (o *DeleteTruckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete truck params
func (o *DeleteTruckParams) WithID(id int64) *DeleteTruckParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete truck params
func (o *DeleteTruckParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTruckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
