// Code generated by go-swagger; DO NOT EDIT.

package delete_truck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kurirmoo/gen/models"
)

// DeleteTruckReader is a Reader for the DeleteTruck structure.
type DeleteTruckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTruckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTruckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteTruckNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTruckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteTruckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteTruckOK creates a DeleteTruckOK with default headers values
func NewDeleteTruckOK() *DeleteTruckOK {
	return &DeleteTruckOK{}
}

/*
DeleteTruckOK describes a response with status code 200, with default header values.

OK
*/
type DeleteTruckOK struct {
	Payload *models.Success
}

// IsSuccess returns true when this delete truck o k response has a 2xx status code
func (o *DeleteTruckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete truck o k response has a 3xx status code
func (o *DeleteTruckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete truck o k response has a 4xx status code
func (o *DeleteTruckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete truck o k response has a 5xx status code
func (o *DeleteTruckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete truck o k response a status code equal to that given
func (o *DeleteTruckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete truck o k response
func (o *DeleteTruckOK) Code() int {
	return 200
}

func (o *DeleteTruckOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckOK  %+v", 200, o.Payload)
}

func (o *DeleteTruckOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckOK  %+v", 200, o.Payload)
}

func (o *DeleteTruckOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *DeleteTruckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTruckNoContent creates a DeleteTruckNoContent with default headers values
func NewDeleteTruckNoContent() *DeleteTruckNoContent {
	return &DeleteTruckNoContent{}
}

/*
DeleteTruckNoContent describes a response with status code 204, with default header values.

Deleted
*/
type DeleteTruckNoContent struct {
	Payload *models.Success
}

// IsSuccess returns true when this delete truck no content response has a 2xx status code
func (o *DeleteTruckNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete truck no content response has a 3xx status code
func (o *DeleteTruckNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete truck no content response has a 4xx status code
func (o *DeleteTruckNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete truck no content response has a 5xx status code
func (o *DeleteTruckNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete truck no content response a status code equal to that given
func (o *DeleteTruckNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete truck no content response
func (o *DeleteTruckNoContent) Code() int {
	return 204
}

func (o *DeleteTruckNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckNoContent  %+v", 204, o.Payload)
}

func (o *DeleteTruckNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckNoContent  %+v", 204, o.Payload)
}

func (o *DeleteTruckNoContent) GetPayload() *models.Success {
	return o.Payload
}

func (o *DeleteTruckNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTruckBadRequest creates a DeleteTruckBadRequest with default headers values
func NewDeleteTruckBadRequest() *DeleteTruckBadRequest {
	return &DeleteTruckBadRequest{}
}

/*
DeleteTruckBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteTruckBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete truck bad request response has a 2xx status code
func (o *DeleteTruckBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete truck bad request response has a 3xx status code
func (o *DeleteTruckBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete truck bad request response has a 4xx status code
func (o *DeleteTruckBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete truck bad request response has a 5xx status code
func (o *DeleteTruckBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete truck bad request response a status code equal to that given
func (o *DeleteTruckBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete truck bad request response
func (o *DeleteTruckBadRequest) Code() int {
	return 400
}

func (o *DeleteTruckBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteTruckBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruckBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteTruckBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteTruckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTruckDefault creates a DeleteTruckDefault with default headers values
func NewDeleteTruckDefault(code int) *DeleteTruckDefault {
	return &DeleteTruckDefault{
		_statusCode: code,
	}
}

/*
DeleteTruckDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteTruckDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this delete truck default response has a 2xx status code
func (o *DeleteTruckDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete truck default response has a 3xx status code
func (o *DeleteTruckDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete truck default response has a 4xx status code
func (o *DeleteTruckDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete truck default response has a 5xx status code
func (o *DeleteTruckDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete truck default response a status code equal to that given
func (o *DeleteTruckDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete truck default response
func (o *DeleteTruckDefault) Code() int {
	return o._statusCode
}

func (o *DeleteTruckDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruck default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteTruckDefault) String() string {
	return fmt.Sprintf("[DELETE /api/v1/trucks/{id}][%d] deleteTruck default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteTruckDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteTruckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
