// Code generated by go-swagger; DO NOT EDIT.

package cities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllCitiesParams creates a new GetAllCitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllCitiesParams() *GetAllCitiesParams {
	return &GetAllCitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllCitiesParamsWithTimeout creates a new GetAllCitiesParams object
// with the ability to set a timeout on a request.
func NewGetAllCitiesParamsWithTimeout(timeout time.Duration) *GetAllCitiesParams {
	return &GetAllCitiesParams{
		timeout: timeout,
	}
}

// NewGetAllCitiesParamsWithContext creates a new GetAllCitiesParams object
// with the ability to set a context for a request.
func NewGetAllCitiesParamsWithContext(ctx context.Context) *GetAllCitiesParams {
	return &GetAllCitiesParams{
		Context: ctx,
	}
}

// NewGetAllCitiesParamsWithHTTPClient creates a new GetAllCitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllCitiesParamsWithHTTPClient(client *http.Client) *GetAllCitiesParams {
	return &GetAllCitiesParams{
		HTTPClient: client,
	}
}

/*
GetAllCitiesParams contains all the parameters to send to the API endpoint

	for the get all cities operation.

	Typically these are written to a http.Request.
*/
type GetAllCitiesParams struct {

	/* CityName.

	   filter with name
	*/
	CityName *string

	/* Limit.

	   filter for limit

	   Default: 10
	*/
	Limit *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all cities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCitiesParams) WithDefaults() *GetAllCitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all cities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCitiesParams) SetDefaults() {
	var (
		limitDefault = int64(10)
	)

	val := GetAllCitiesParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get all cities params
func (o *GetAllCitiesParams) WithTimeout(timeout time.Duration) *GetAllCitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all cities params
func (o *GetAllCitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all cities params
func (o *GetAllCitiesParams) WithContext(ctx context.Context) *GetAllCitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all cities params
func (o *GetAllCitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all cities params
func (o *GetAllCitiesParams) WithHTTPClient(client *http.Client) *GetAllCitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all cities params
func (o *GetAllCitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCityName adds the cityName to the get all cities params
func (o *GetAllCitiesParams) WithCityName(cityName *string) *GetAllCitiesParams {
	o.SetCityName(cityName)
	return o
}

// SetCityName adds the cityName to the get all cities params
func (o *GetAllCitiesParams) SetCityName(cityName *string) {
	o.CityName = cityName
}

// WithLimit adds the limit to the get all cities params
func (o *GetAllCitiesParams) WithLimit(limit *int64) *GetAllCitiesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all cities params
func (o *GetAllCitiesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllCitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CityName != nil {

		// query param city_name
		var qrCityName string

		if o.CityName != nil {
			qrCityName = *o.CityName
		}
		qCityName := qrCityName
		if qCityName != "" {

			if err := r.SetQueryParam("city_name", qCityName); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
