// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllCustomerParams creates a new GetAllCustomerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllCustomerParams() *GetAllCustomerParams {
	return &GetAllCustomerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllCustomerParamsWithTimeout creates a new GetAllCustomerParams object
// with the ability to set a timeout on a request.
func NewGetAllCustomerParamsWithTimeout(timeout time.Duration) *GetAllCustomerParams {
	return &GetAllCustomerParams{
		timeout: timeout,
	}
}

// NewGetAllCustomerParamsWithContext creates a new GetAllCustomerParams object
// with the ability to set a context for a request.
func NewGetAllCustomerParamsWithContext(ctx context.Context) *GetAllCustomerParams {
	return &GetAllCustomerParams{
		Context: ctx,
	}
}

// NewGetAllCustomerParamsWithHTTPClient creates a new GetAllCustomerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllCustomerParamsWithHTTPClient(client *http.Client) *GetAllCustomerParams {
	return &GetAllCustomerParams{
		HTTPClient: client,
	}
}

/*
GetAllCustomerParams contains all the parameters to send to the API endpoint

	for the get all customer operation.

	Typically these are written to a http.Request.
*/
type GetAllCustomerParams struct {

	/* Name.

	   search with name
	*/
	Name *string

	/* Status.

	   filter for status
	*/
	Status *string

	/* Type.

	   filter for type
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCustomerParams) WithDefaults() *GetAllCustomerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCustomerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all customer params
func (o *GetAllCustomerParams) WithTimeout(timeout time.Duration) *GetAllCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all customer params
func (o *GetAllCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all customer params
func (o *GetAllCustomerParams) WithContext(ctx context.Context) *GetAllCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all customer params
func (o *GetAllCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all customer params
func (o *GetAllCustomerParams) WithHTTPClient(client *http.Client) *GetAllCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all customer params
func (o *GetAllCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get all customer params
func (o *GetAllCustomerParams) WithName(name *string) *GetAllCustomerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get all customer params
func (o *GetAllCustomerParams) SetName(name *string) {
	o.Name = name
}

// WithStatus adds the status to the get all customer params
func (o *GetAllCustomerParams) WithStatus(status *string) *GetAllCustomerParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get all customer params
func (o *GetAllCustomerParams) SetStatus(status *string) {
	o.Status = status
}

// WithType adds the typeVar to the get all customer params
func (o *GetAllCustomerParams) WithType(typeVar *string) *GetAllCustomerParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get all customer params
func (o *GetAllCustomerParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Status != nil {

		// query param status
		var qrStatus string

		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {

			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
