// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"kurirmoo/gen/models"
)

// GetAllCustomerReader is a Reader for the GetAllCustomer structure.
type GetAllCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllCustomerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetAllCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAllCustomerOK creates a GetAllCustomerOK with default headers values
func NewGetAllCustomerOK() *GetAllCustomerOK {
	return &GetAllCustomerOK{}
}

/*
GetAllCustomerOK describes a response with status code 200, with default header values.

a json array of customers
*/
type GetAllCustomerOK struct {
	Payload []*GetAllCustomerOKBodyItems0
}

// IsSuccess returns true when this get all customer o k response has a 2xx status code
func (o *GetAllCustomerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all customer o k response has a 3xx status code
func (o *GetAllCustomerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all customer o k response has a 4xx status code
func (o *GetAllCustomerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all customer o k response has a 5xx status code
func (o *GetAllCustomerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all customer o k response a status code equal to that given
func (o *GetAllCustomerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all customer o k response
func (o *GetAllCustomerOK) Code() int {
	return 200
}

func (o *GetAllCustomerOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomerOK  %+v", 200, o.Payload)
}

func (o *GetAllCustomerOK) String() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomerOK  %+v", 200, o.Payload)
}

func (o *GetAllCustomerOK) GetPayload() []*GetAllCustomerOKBodyItems0 {
	return o.Payload
}

func (o *GetAllCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllCustomerBadRequest creates a GetAllCustomerBadRequest with default headers values
func NewGetAllCustomerBadRequest() *GetAllCustomerBadRequest {
	return &GetAllCustomerBadRequest{}
}

/*
GetAllCustomerBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAllCustomerBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get all customer bad request response has a 2xx status code
func (o *GetAllCustomerBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all customer bad request response has a 3xx status code
func (o *GetAllCustomerBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all customer bad request response has a 4xx status code
func (o *GetAllCustomerBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all customer bad request response has a 5xx status code
func (o *GetAllCustomerBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get all customer bad request response a status code equal to that given
func (o *GetAllCustomerBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get all customer bad request response
func (o *GetAllCustomerBadRequest) Code() int {
	return 400
}

func (o *GetAllCustomerBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomerBadRequest  %+v", 400, o.Payload)
}

func (o *GetAllCustomerBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomerBadRequest  %+v", 400, o.Payload)
}

func (o *GetAllCustomerBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAllCustomerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllCustomerDefault creates a GetAllCustomerDefault with default headers values
func NewGetAllCustomerDefault(code int) *GetAllCustomerDefault {
	return &GetAllCustomerDefault{
		_statusCode: code,
	}
}

/*
GetAllCustomerDefault describes a response with status code -1, with default header values.

error
*/
type GetAllCustomerDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get all customer default response has a 2xx status code
func (o *GetAllCustomerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get all customer default response has a 3xx status code
func (o *GetAllCustomerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get all customer default response has a 4xx status code
func (o *GetAllCustomerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get all customer default response has a 5xx status code
func (o *GetAllCustomerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get all customer default response a status code equal to that given
func (o *GetAllCustomerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get all customer default response
func (o *GetAllCustomerDefault) Code() int {
	return o._statusCode
}

func (o *GetAllCustomerDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllCustomerDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/customers][%d] getAllCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllCustomerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAllCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetAllCustomerOKBodyItems0 get all customer o k body items0
swagger:model GetAllCustomerOKBodyItems0
*/
type GetAllCustomerOKBodyItems0 struct {

	// account status
	AccountStatus string `json:"account_status,omitempty"`

	// created at
	CreatedAt int64 `json:"created_at" gorm:"type:int;autoCreateTime"`

	// id
	ID int64 `json:"id,omitempty"`

	// is corporate
	IsCorporate bool `json:"is_corporate,omitempty"`

	// ktp number
	KtpNumber string `json:"ktp_number,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`
}

// Validate validates this get all customer o k body items0
func (o *GetAllCustomerOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get all customer o k body items0 based on context it is used
func (o *GetAllCustomerOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAllCustomerOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllCustomerOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetAllCustomerOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
