// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthParams creates a new AuthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthParams() *AuthParams {
	return &AuthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthParamsWithTimeout creates a new AuthParams object
// with the ability to set a timeout on a request.
func NewAuthParamsWithTimeout(timeout time.Duration) *AuthParams {
	return &AuthParams{
		timeout: timeout,
	}
}

// NewAuthParamsWithContext creates a new AuthParams object
// with the ability to set a context for a request.
func NewAuthParamsWithContext(ctx context.Context) *AuthParams {
	return &AuthParams{
		Context: ctx,
	}
}

// NewAuthParamsWithHTTPClient creates a new AuthParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthParamsWithHTTPClient(client *http.Client) *AuthParams {
	return &AuthParams{
		HTTPClient: client,
	}
}

/*
AuthParams contains all the parameters to send to the API endpoint

	for the auth operation.

	Typically these are written to a http.Request.
*/
type AuthParams struct {

	// Data.
	Data AuthBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthParams) WithDefaults() *AuthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth params
func (o *AuthParams) WithTimeout(timeout time.Duration) *AuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth params
func (o *AuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth params
func (o *AuthParams) WithContext(ctx context.Context) *AuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth params
func (o *AuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth params
func (o *AuthParams) WithHTTPClient(client *http.Client) *AuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth params
func (o *AuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the auth params
func (o *AuthParams) WithData(data AuthBody) *AuthParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the auth params
func (o *AuthParams) SetData(data AuthBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *AuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
