// Code generated by go-swagger; DO NOT EDIT.

package update_driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateDriverParams creates a new UpdateDriverParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDriverParams() *UpdateDriverParams {
	return &UpdateDriverParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDriverParamsWithTimeout creates a new UpdateDriverParams object
// with the ability to set a timeout on a request.
func NewUpdateDriverParamsWithTimeout(timeout time.Duration) *UpdateDriverParams {
	return &UpdateDriverParams{
		timeout: timeout,
	}
}

// NewUpdateDriverParamsWithContext creates a new UpdateDriverParams object
// with the ability to set a context for a request.
func NewUpdateDriverParamsWithContext(ctx context.Context) *UpdateDriverParams {
	return &UpdateDriverParams{
		Context: ctx,
	}
}

// NewUpdateDriverParamsWithHTTPClient creates a new UpdateDriverParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDriverParamsWithHTTPClient(client *http.Client) *UpdateDriverParams {
	return &UpdateDriverParams{
		HTTPClient: client,
	}
}

/*
UpdateDriverParams contains all the parameters to send to the API endpoint

	for the update driver operation.

	Typically these are written to a http.Request.
*/
type UpdateDriverParams struct {

	// Data.
	Data UpdateDriverBody

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update driver params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDriverParams) WithDefaults() *UpdateDriverParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update driver params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDriverParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update driver params
func (o *UpdateDriverParams) WithTimeout(timeout time.Duration) *UpdateDriverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update driver params
func (o *UpdateDriverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update driver params
func (o *UpdateDriverParams) WithContext(ctx context.Context) *UpdateDriverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update driver params
func (o *UpdateDriverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update driver params
func (o *UpdateDriverParams) WithHTTPClient(client *http.Client) *UpdateDriverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update driver params
func (o *UpdateDriverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the update driver params
func (o *UpdateDriverParams) WithData(data UpdateDriverBody) *UpdateDriverParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the update driver params
func (o *UpdateDriverParams) SetData(data UpdateDriverBody) {
	o.Data = data
}

// WithID adds the id to the update driver params
func (o *UpdateDriverParams) WithID(id int64) *UpdateDriverParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update driver params
func (o *UpdateDriverParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDriverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
