// Code generated by go-swagger; DO NOT EDIT.

package detail_data_multiplier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new detail data multiplier API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for detail data multiplier API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetDetailDataMultiplier(params *GetDetailDataMultiplierParams, opts ...ClientOption) (*GetDetailDataMultiplierOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetDetailDataMultiplier gets detail data multiplier

Return detail data multiplier
*/
func (a *Client) GetDetailDataMultiplier(params *GetDetailDataMultiplierParams, opts ...ClientOption) (*GetDetailDataMultiplierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDetailDataMultiplierParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getDetailDataMultiplier",
		Method:             "GET",
		PathPattern:        "/api/v1/data_multipliers/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetDetailDataMultiplierReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDetailDataMultiplierOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetDetailDataMultiplierDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
