// Code generated by go-swagger; DO NOT EDIT.

package detail_data_multiplier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDetailDataMultiplierParams creates a new GetDetailDataMultiplierParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDetailDataMultiplierParams() *GetDetailDataMultiplierParams {
	return &GetDetailDataMultiplierParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDetailDataMultiplierParamsWithTimeout creates a new GetDetailDataMultiplierParams object
// with the ability to set a timeout on a request.
func NewGetDetailDataMultiplierParamsWithTimeout(timeout time.Duration) *GetDetailDataMultiplierParams {
	return &GetDetailDataMultiplierParams{
		timeout: timeout,
	}
}

// NewGetDetailDataMultiplierParamsWithContext creates a new GetDetailDataMultiplierParams object
// with the ability to set a context for a request.
func NewGetDetailDataMultiplierParamsWithContext(ctx context.Context) *GetDetailDataMultiplierParams {
	return &GetDetailDataMultiplierParams{
		Context: ctx,
	}
}

// NewGetDetailDataMultiplierParamsWithHTTPClient creates a new GetDetailDataMultiplierParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDetailDataMultiplierParamsWithHTTPClient(client *http.Client) *GetDetailDataMultiplierParams {
	return &GetDetailDataMultiplierParams{
		HTTPClient: client,
	}
}

/*
GetDetailDataMultiplierParams contains all the parameters to send to the API endpoint

	for the get detail data multiplier operation.

	Typically these are written to a http.Request.
*/
type GetDetailDataMultiplierParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get detail data multiplier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetailDataMultiplierParams) WithDefaults() *GetDetailDataMultiplierParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get detail data multiplier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetailDataMultiplierParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) WithTimeout(timeout time.Duration) *GetDetailDataMultiplierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) WithContext(ctx context.Context) *GetDetailDataMultiplierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) WithHTTPClient(client *http.Client) *GetDetailDataMultiplierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) WithID(id string) *GetDetailDataMultiplierParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get detail data multiplier params
func (o *GetDetailDataMultiplierParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDetailDataMultiplierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
