// Code generated by go-swagger; DO NOT EDIT.

package detail_data_multiplier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"kurirmoo/gen/models"
)

// GetDetailDataMultiplierReader is a Reader for the GetDetailDataMultiplier structure.
type GetDetailDataMultiplierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDetailDataMultiplierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDetailDataMultiplierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDetailDataMultiplierBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDetailDataMultiplierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDetailDataMultiplierInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetDetailDataMultiplierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDetailDataMultiplierOK creates a GetDetailDataMultiplierOK with default headers values
func NewGetDetailDataMultiplierOK() *GetDetailDataMultiplierOK {
	return &GetDetailDataMultiplierOK{}
}

/*
GetDetailDataMultiplierOK describes a response with status code 200, with default header values.

A JSON of detail data multiplier
*/
type GetDetailDataMultiplierOK struct {
	Payload *GetDetailDataMultiplierOKBody
}

// IsSuccess returns true when this get detail data multiplier o k response has a 2xx status code
func (o *GetDetailDataMultiplierOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get detail data multiplier o k response has a 3xx status code
func (o *GetDetailDataMultiplierOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detail data multiplier o k response has a 4xx status code
func (o *GetDetailDataMultiplierOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get detail data multiplier o k response has a 5xx status code
func (o *GetDetailDataMultiplierOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get detail data multiplier o k response a status code equal to that given
func (o *GetDetailDataMultiplierOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get detail data multiplier o k response
func (o *GetDetailDataMultiplierOK) Code() int {
	return 200
}

func (o *GetDetailDataMultiplierOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierOK  %+v", 200, o.Payload)
}

func (o *GetDetailDataMultiplierOK) String() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierOK  %+v", 200, o.Payload)
}

func (o *GetDetailDataMultiplierOK) GetPayload() *GetDetailDataMultiplierOKBody {
	return o.Payload
}

func (o *GetDetailDataMultiplierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDetailDataMultiplierOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailDataMultiplierBadRequest creates a GetDetailDataMultiplierBadRequest with default headers values
func NewGetDetailDataMultiplierBadRequest() *GetDetailDataMultiplierBadRequest {
	return &GetDetailDataMultiplierBadRequest{}
}

/*
GetDetailDataMultiplierBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetDetailDataMultiplierBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get detail data multiplier bad request response has a 2xx status code
func (o *GetDetailDataMultiplierBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get detail data multiplier bad request response has a 3xx status code
func (o *GetDetailDataMultiplierBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detail data multiplier bad request response has a 4xx status code
func (o *GetDetailDataMultiplierBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get detail data multiplier bad request response has a 5xx status code
func (o *GetDetailDataMultiplierBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get detail data multiplier bad request response a status code equal to that given
func (o *GetDetailDataMultiplierBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get detail data multiplier bad request response
func (o *GetDetailDataMultiplierBadRequest) Code() int {
	return 400
}

func (o *GetDetailDataMultiplierBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierBadRequest  %+v", 400, o.Payload)
}

func (o *GetDetailDataMultiplierBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierBadRequest  %+v", 400, o.Payload)
}

func (o *GetDetailDataMultiplierBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDetailDataMultiplierBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailDataMultiplierNotFound creates a GetDetailDataMultiplierNotFound with default headers values
func NewGetDetailDataMultiplierNotFound() *GetDetailDataMultiplierNotFound {
	return &GetDetailDataMultiplierNotFound{}
}

/*
GetDetailDataMultiplierNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type GetDetailDataMultiplierNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get detail data multiplier not found response has a 2xx status code
func (o *GetDetailDataMultiplierNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get detail data multiplier not found response has a 3xx status code
func (o *GetDetailDataMultiplierNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detail data multiplier not found response has a 4xx status code
func (o *GetDetailDataMultiplierNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get detail data multiplier not found response has a 5xx status code
func (o *GetDetailDataMultiplierNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get detail data multiplier not found response a status code equal to that given
func (o *GetDetailDataMultiplierNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get detail data multiplier not found response
func (o *GetDetailDataMultiplierNotFound) Code() int {
	return 404
}

func (o *GetDetailDataMultiplierNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierNotFound  %+v", 404, o.Payload)
}

func (o *GetDetailDataMultiplierNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierNotFound  %+v", 404, o.Payload)
}

func (o *GetDetailDataMultiplierNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDetailDataMultiplierNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailDataMultiplierInternalServerError creates a GetDetailDataMultiplierInternalServerError with default headers values
func NewGetDetailDataMultiplierInternalServerError() *GetDetailDataMultiplierInternalServerError {
	return &GetDetailDataMultiplierInternalServerError{}
}

/*
GetDetailDataMultiplierInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetDetailDataMultiplierInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get detail data multiplier internal server error response has a 2xx status code
func (o *GetDetailDataMultiplierInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get detail data multiplier internal server error response has a 3xx status code
func (o *GetDetailDataMultiplierInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get detail data multiplier internal server error response has a 4xx status code
func (o *GetDetailDataMultiplierInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get detail data multiplier internal server error response has a 5xx status code
func (o *GetDetailDataMultiplierInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get detail data multiplier internal server error response a status code equal to that given
func (o *GetDetailDataMultiplierInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get detail data multiplier internal server error response
func (o *GetDetailDataMultiplierInternalServerError) Code() int {
	return 500
}

func (o *GetDetailDataMultiplierInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDetailDataMultiplierInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplierInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDetailDataMultiplierInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDetailDataMultiplierInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailDataMultiplierDefault creates a GetDetailDataMultiplierDefault with default headers values
func NewGetDetailDataMultiplierDefault(code int) *GetDetailDataMultiplierDefault {
	return &GetDetailDataMultiplierDefault{
		_statusCode: code,
	}
}

/*
GetDetailDataMultiplierDefault describes a response with status code -1, with default header values.

error
*/
type GetDetailDataMultiplierDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get detail data multiplier default response has a 2xx status code
func (o *GetDetailDataMultiplierDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get detail data multiplier default response has a 3xx status code
func (o *GetDetailDataMultiplierDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get detail data multiplier default response has a 4xx status code
func (o *GetDetailDataMultiplierDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get detail data multiplier default response has a 5xx status code
func (o *GetDetailDataMultiplierDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get detail data multiplier default response a status code equal to that given
func (o *GetDetailDataMultiplierDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get detail data multiplier default response
func (o *GetDetailDataMultiplierDefault) Code() int {
	return o._statusCode
}

func (o *GetDetailDataMultiplierDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplier default  %+v", o._statusCode, o.Payload)
}

func (o *GetDetailDataMultiplierDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/data_multipliers/{id}][%d] getDetailDataMultiplier default  %+v", o._statusCode, o.Payload)
}

func (o *GetDetailDataMultiplierDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDetailDataMultiplierDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetDetailDataMultiplierOKBody get detail data multiplier o k body
swagger:model GetDetailDataMultiplierOKBody
*/
type GetDetailDataMultiplierOKBody struct {

	// brand
	Brand string `json:"brand,omitempty"`

	// capacity
	Capacity int64 `json:"capacity,omitempty"`

	// city passed
	CityPassed int64 `json:"city_passed,omitempty"`

	// distance
	Distance int64 `json:"distance,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// lane
	Lane string `json:"lane,omitempty"`

	// max price
	MaxPrice int64 `json:"max_price,omitempty"`

	// min price
	MinPrice int64 `json:"min_price,omitempty"`

	// price per km
	PricePerKm int64 `json:"price_per_km,omitempty"`

	// route
	Route string `json:"route,omitempty"`

	// truck kind
	TruckKind string `json:"truck_kind,omitempty"`

	// truck type
	TruckType string `json:"truck_type,omitempty"`

	// volume
	Volume int64 `json:"volume,omitempty"`
}

// Validate validates this get detail data multiplier o k body
func (o *GetDetailDataMultiplierOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get detail data multiplier o k body based on context it is used
func (o *GetDetailDataMultiplierOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDetailDataMultiplierOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDetailDataMultiplierOKBody) UnmarshalBinary(b []byte) error {
	var res GetDetailDataMultiplierOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
