// Code generated by go-swagger; DO NOT EDIT.

package otp_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostRequestWhatsappParams creates a new PostRequestWhatsappParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRequestWhatsappParams() *PostRequestWhatsappParams {
	return &PostRequestWhatsappParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRequestWhatsappParamsWithTimeout creates a new PostRequestWhatsappParams object
// with the ability to set a timeout on a request.
func NewPostRequestWhatsappParamsWithTimeout(timeout time.Duration) *PostRequestWhatsappParams {
	return &PostRequestWhatsappParams{
		timeout: timeout,
	}
}

// NewPostRequestWhatsappParamsWithContext creates a new PostRequestWhatsappParams object
// with the ability to set a context for a request.
func NewPostRequestWhatsappParamsWithContext(ctx context.Context) *PostRequestWhatsappParams {
	return &PostRequestWhatsappParams{
		Context: ctx,
	}
}

// NewPostRequestWhatsappParamsWithHTTPClient creates a new PostRequestWhatsappParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRequestWhatsappParamsWithHTTPClient(client *http.Client) *PostRequestWhatsappParams {
	return &PostRequestWhatsappParams{
		HTTPClient: client,
	}
}

/*
PostRequestWhatsappParams contains all the parameters to send to the API endpoint

	for the post request whatsapp operation.

	Typically these are written to a http.Request.
*/
type PostRequestWhatsappParams struct {

	// Data.
	Data PostRequestWhatsappBody

	// ID.
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post request whatsapp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRequestWhatsappParams) WithDefaults() *PostRequestWhatsappParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post request whatsapp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRequestWhatsappParams) SetDefaults() {
	var (
		idDefault = string("")
	)

	val := PostRequestWhatsappParams{
		ID: &idDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post request whatsapp params
func (o *PostRequestWhatsappParams) WithTimeout(timeout time.Duration) *PostRequestWhatsappParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post request whatsapp params
func (o *PostRequestWhatsappParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post request whatsapp params
func (o *PostRequestWhatsappParams) WithContext(ctx context.Context) *PostRequestWhatsappParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post request whatsapp params
func (o *PostRequestWhatsappParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post request whatsapp params
func (o *PostRequestWhatsappParams) WithHTTPClient(client *http.Client) *PostRequestWhatsappParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post request whatsapp params
func (o *PostRequestWhatsappParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post request whatsapp params
func (o *PostRequestWhatsappParams) WithData(data PostRequestWhatsappBody) *PostRequestWhatsappParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post request whatsapp params
func (o *PostRequestWhatsappParams) SetData(data PostRequestWhatsappBody) {
	o.Data = data
}

// WithID adds the id to the post request whatsapp params
func (o *PostRequestWhatsappParams) WithID(id *string) *PostRequestWhatsappParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post request whatsapp params
func (o *PostRequestWhatsappParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRequestWhatsappParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
