// Code generated by go-swagger; DO NOT EDIT.

package get_route_and_city_passeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRouteAndCityPassedsParams creates a new GetRouteAndCityPassedsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRouteAndCityPassedsParams() *GetRouteAndCityPassedsParams {
	return &GetRouteAndCityPassedsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRouteAndCityPassedsParamsWithTimeout creates a new GetRouteAndCityPassedsParams object
// with the ability to set a timeout on a request.
func NewGetRouteAndCityPassedsParamsWithTimeout(timeout time.Duration) *GetRouteAndCityPassedsParams {
	return &GetRouteAndCityPassedsParams{
		timeout: timeout,
	}
}

// NewGetRouteAndCityPassedsParamsWithContext creates a new GetRouteAndCityPassedsParams object
// with the ability to set a context for a request.
func NewGetRouteAndCityPassedsParamsWithContext(ctx context.Context) *GetRouteAndCityPassedsParams {
	return &GetRouteAndCityPassedsParams{
		Context: ctx,
	}
}

// NewGetRouteAndCityPassedsParamsWithHTTPClient creates a new GetRouteAndCityPassedsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRouteAndCityPassedsParamsWithHTTPClient(client *http.Client) *GetRouteAndCityPassedsParams {
	return &GetRouteAndCityPassedsParams{
		HTTPClient: client,
	}
}

/*
GetRouteAndCityPassedsParams contains all the parameters to send to the API endpoint

	for the get route and city passeds operation.

	Typically these are written to a http.Request.
*/
type GetRouteAndCityPassedsParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get route and city passeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAndCityPassedsParams) WithDefaults() *GetRouteAndCityPassedsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get route and city passeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAndCityPassedsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) WithTimeout(timeout time.Duration) *GetRouteAndCityPassedsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) WithContext(ctx context.Context) *GetRouteAndCityPassedsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) WithHTTPClient(client *http.Client) *GetRouteAndCityPassedsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) WithID(id int64) *GetRouteAndCityPassedsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get route and city passeds params
func (o *GetRouteAndCityPassedsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRouteAndCityPassedsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
