// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"kurirmoo/gen/models"
)

// HealthReader is a Reader for the Health structure.
type HealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewHealthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /health] health", response, response.Code())
	}
}

// NewHealthOK creates a HealthOK with default headers values
func NewHealthOK() *HealthOK {
	return &HealthOK{}
}

/*
HealthOK describes a response with status code 200, with default header values.

Health Check
*/
type HealthOK struct {
	Payload *models.Success
}

// IsSuccess returns true when this health o k response has a 2xx status code
func (o *HealthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this health o k response has a 3xx status code
func (o *HealthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health o k response has a 4xx status code
func (o *HealthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this health o k response has a 5xx status code
func (o *HealthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this health o k response a status code equal to that given
func (o *HealthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the health o k response
func (o *HealthOK) Code() int {
	return 200
}

func (o *HealthOK) Error() string {
	return fmt.Sprintf("[GET /health][%d] healthOK  %+v", 200, o.Payload)
}

func (o *HealthOK) String() string {
	return fmt.Sprintf("[GET /health][%d] healthOK  %+v", 200, o.Payload)
}

func (o *HealthOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *HealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHealthInternalServerError creates a HealthInternalServerError with default headers values
func NewHealthInternalServerError() *HealthInternalServerError {
	return &HealthInternalServerError{}
}

/*
HealthInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type HealthInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this health internal server error response has a 2xx status code
func (o *HealthInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this health internal server error response has a 3xx status code
func (o *HealthInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health internal server error response has a 4xx status code
func (o *HealthInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this health internal server error response has a 5xx status code
func (o *HealthInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this health internal server error response a status code equal to that given
func (o *HealthInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the health internal server error response
func (o *HealthInternalServerError) Code() int {
	return 500
}

func (o *HealthInternalServerError) Error() string {
	return fmt.Sprintf("[GET /health][%d] healthInternalServerError  %+v", 500, o.Payload)
}

func (o *HealthInternalServerError) String() string {
	return fmt.Sprintf("[GET /health][%d] healthInternalServerError  %+v", 500, o.Payload)
}

func (o *HealthInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *HealthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
