// Code generated by go-swagger; DO NOT EDIT.

package trucks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddTruckParams creates a new AddTruckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddTruckParams() *AddTruckParams {
	return &AddTruckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddTruckParamsWithTimeout creates a new AddTruckParams object
// with the ability to set a timeout on a request.
func NewAddTruckParamsWithTimeout(timeout time.Duration) *AddTruckParams {
	return &AddTruckParams{
		timeout: timeout,
	}
}

// NewAddTruckParamsWithContext creates a new AddTruckParams object
// with the ability to set a context for a request.
func NewAddTruckParamsWithContext(ctx context.Context) *AddTruckParams {
	return &AddTruckParams{
		Context: ctx,
	}
}

// NewAddTruckParamsWithHTTPClient creates a new AddTruckParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddTruckParamsWithHTTPClient(client *http.Client) *AddTruckParams {
	return &AddTruckParams{
		HTTPClient: client,
	}
}

/*
AddTruckParams contains all the parameters to send to the API endpoint

	for the add truck operation.

	Typically these are written to a http.Request.
*/
type AddTruckParams struct {

	// Data.
	Data AddTruckBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add truck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTruckParams) WithDefaults() *AddTruckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add truck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTruckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add truck params
func (o *AddTruckParams) WithTimeout(timeout time.Duration) *AddTruckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add truck params
func (o *AddTruckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add truck params
func (o *AddTruckParams) WithContext(ctx context.Context) *AddTruckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add truck params
func (o *AddTruckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add truck params
func (o *AddTruckParams) WithHTTPClient(client *http.Client) *AddTruckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add truck params
func (o *AddTruckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the add truck params
func (o *AddTruckParams) WithData(data AddTruckBody) *AddTruckParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the add truck params
func (o *AddTruckParams) SetData(data AddTruckBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *AddTruckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
